#!/bin/bash

# workmux refuses to operate on a repo whose .git/hooks entries are symlinks or
# hardlinks, and it reads .git/hooks directly: core.hooksPath does not move the
# check. mm_website's git/setup.sh installs its hooks as symlinks, so replace
# each one with a regular file that sources the real hook.
#
# Re-run after git/setup.sh, which restores the symlinks.

set -eu

echo 'git hooks'

for repo in "${@:-/workspaces/mmwebsite}"; do
  hooks="$repo/.git/hooks"
  [ -d "$hooks" ] || continue

  for hook in "$hooks"/*; do
    [ -L "$hook" ] || continue
    name=$(basename "$hook")
    target=$(readlink -f "$hook")

    # Git silently skips a dangling symlink. A wrapper would run and fail with
    # 127, so drop it rather than preserve it.
    if [ ! -e "$target" ]; then
      rm -f "$hook"
      echo "  removed dangling hook $name"
      continue
    fi

    rm -f "$hook"
    cat >"$hook" <<EOF
#!/bin/bash
# Generated by dotfiles configure/git-hooks.sh. A regular file, not a symlink:
# workmux refuses to run when .git hooks are symlinks. \`source\` keeps \$0,
# which hook-chain reads to find the hook name.
source "$target"
EOF
    chmod +x "$hook"
    echo "  unlinked hook $name"
  done
done
